#
# A simple makefile for compiling a c++ project
#
.DEFAULT_GOAL := CoinFlipper.cpp

all: clean test

CoinFlipper.cpp: 
	gcc -o ./target/CoinFlipper.out ./src/main/CoinFlipper.cpp

run: CoinFlipper.cpp
	./target/CoinFlipper.out 10

test: CoinFlipper.cpp
	./target/CoinFlipper.out 10000

clean: 
	rm -rf ./target/*.out